services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-wallet
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "password123"
      ACCEPT_EULA: "Y"
